name: ROS2 listener test

on: push

jobs:
  test:
    runs-on: ubuntu-22.04
    container: ryuichiueda/ubuntu22.04-ros2:latest

    steps:
      - uses: actions/checkout@v4

      - name: Build ROS2 workspace
        shell: bash
        run: |
          set -e
          source /opt/ros/humble/setup.bash

          mkdir -p /root/ros2_ws/src
          rsync -av ./ /root/ros2_ws/src/mypkg/

          cd /root/ros2_ws
          colcon build

      - name: Run listener test
        shell: bash
        run: |
          chmod +x /root/ros2_ws/src/mypkg/test/test.bash
          /root/ros2_ws/src/mypkg/test/test.bash /root/ros2_ws
